In [33]:
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\chidv\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

## Step 1: Data Loading

In [17]:

badminton = pd.read_csv(r"D:\DS\Projects\GEN_AI\TASK_2\Sentiment Analysis\reviews_badminton\data.csv")
tawa = pd.read_csv(r"D:\DS\Projects\GEN_AI\TASK_2\Sentiment Analysis\reviews_tawa\data.csv")
tea = pd.read_csv(r"D:\DS\Projects\GEN_AI\TASK_2\Sentiment Analysis\reviews_tea\data.csv")

In [52]:
tea.shape

(9170, 9)

In [19]:
tawa.columns

Index(['Reviewer_Name', 'Reviewer_Rating', 'Review_Title', 'Review_Text',
       'Place_of_Review', 'Date_of_Review', 'Up_Votes', 'Down_Votes'],
      dtype='object')

In [20]:
badminton.columns

Index(['Reviewer Name', 'Review Title', 'Place of Review', 'Up Votes',
       'Down Votes', 'Month', 'Review text', 'Ratings'],
      dtype='object')

In [21]:
tea.columns

Index(['reviewer_name', 'reviewer_rating', 'review_title', 'review_text',
       'place_of_review', 'Date_of_review', 'up_votes', 'Down_votes'],
      dtype='object')

## Step 2: Data Cleaning

In [22]:
badminton.columns = badminton.columns.str.strip().str.lower().str.replace(" ", "_")

badminton.rename(columns={
    'ratings': 'reviewer_rating'
}, inplace=True)

In [23]:
tawa.columns = tawa.columns.str.strip().str.lower().str.replace(" ", "_")

In [24]:
tea.columns = tea.columns.str.strip().str.lower().str.replace(" ", "_")

In [25]:
print(badminton.columns)
print(tawa.columns)
print(tea.columns)

Index(['reviewer_name', 'review_title', 'place_of_review', 'up_votes',
       'down_votes', 'month', 'review_text', 'reviewer_rating'],
      dtype='object')
Index(['reviewer_name', 'reviewer_rating', 'review_title', 'review_text',
       'place_of_review', 'date_of_review', 'up_votes', 'down_votes'],
      dtype='object')
Index(['reviewer_name', 'reviewer_rating', 'review_title', 'review_text',
       'place_of_review', 'date_of_review', 'up_votes', 'down_votes'],
      dtype='object')

In [26]:
badminton['date_of_review'] = None
badminton.drop(columns=['month'], inplace=True)

In [27]:
columns_order = [
    'reviewer_name', 'reviewer_rating', 'review_title',
    'review_text', 'place_of_review', 'date_of_review',
    'up_votes', 'down_votes'
]

badminton = badminton[columns_order]
tawa = tawa[columns_order]
tea = tea[columns_order]

In [30]:
badminton.loc[:, 'product'] = 'badminton'
tawa.loc[:, 'product'] = 'tawa'
tea.loc[:, 'product'] = 'tea'

In [71]:
df = pd.concat([badminton, tawa, tea], ignore_index=True)

In [72]:
df

,reviewer_name,reviewer_rating,review_title,review_text,place_of_review,date_of_review,up_votes,down_votes,product
0,Kamal Suresh,4.0,Nice product,"Nice product, good quality, but price is now r...","Certified Buyer, Chirakkal",None,889.0,64.0,badminton
1,Flipkart Customer,1.0,Don't waste your money,They didn't supplied Yonex Mavis 350. Outside ...,"Certified Buyer, Hyderabad",None,109.0,6.0,badminton
2,A. S. Raja Srinivasan,1.0,Did not meet expectations,Worst product. Damaged shuttlecocks packed in ...,"Certified Buyer, Dharmapuri",None,42.0,3.0,badminton
3,Suresh Narayanasamy,3.0,Fair,"Quite O. K. , but nowadays the quality of the...","Certified Buyer, Chennai",None,25.0,1.0,badminton
4,ASHIK P A,1.0,Over priced,Over pricedJust â?¹620 ..from retailer.I didn'...,NaN,None,147.0,24.0,badminton
...,...,...,...,...,...,...,...,...,...
20214,Omm Prakash,5.0,Simply awesome,Nice for red tea.Valeu for moneyREAD MORE,"Certified Buyer, Dhamanagar",Omm Prakash,26.0,5.0,tea
20215,Ritu Raj,4.0,Good choice,niceREAD MORE,"Certified Buyer, Katihar District",Ritu Raj,19.0,4.0,tea
20216,Arun Saini,1.0,Terrible product,Tata Gold Vs Tata Tea Premium👍Tata Tea Premiu...,"Certified Buyer, Haridwar",Arun Saini,13.0,2.0,tea
20217,Amitabh Shahi,5.0,Just wow!,I believe that it's the best packaged tea in t...,"Certified Buyer, Darbhanga",Amitabh Shahi,32.0,10.0,tea
20218,Rohan Bhowmik,5.0,Simply awesome,Very good product.READ MORE,"Certified Buyer, Paschim Medinipur District",Rohan Bhowmik,69.0,29.0,tea

In [73]:
df.shape

(20219, 9)

In [74]:
df.isna().sum()

reviewer_name        10
reviewer_rating     246
review_title         10
review_text           8
place_of_review      50
date_of_review     8518
up_votes             10
down_votes           10
product               0
dtype: int64

In [75]:
df = df.drop(columns=['date_of_review'])

In [76]:
df['review_title'] = df['review_title'].fillna("")
df['place_of_review'] = df['place_of_review'].fillna("unknown")
df['reviewer_rating'] = df['reviewer_rating'].fillna(df['reviewer_rating'].mean())

In [81]:
df['review_text'] = df['review_text'].fillna("")

In [ ]:

df['clean_text'] = df['review_text'].apply(clean_text)

In [82]:
df.isna().sum()

reviewer_name      10
reviewer_rating     0
review_title        0
review_text         0
place_of_review     0
up_votes           10
down_votes         10
product             0
dtype: int64

In [79]:
df

,reviewer_name,reviewer_rating,review_title,review_text,place_of_review,up_votes,down_votes,product
0,Kamal Suresh,4.0,Nice product,"Nice product, good quality, but price is now r...","Certified Buyer, Chirakkal",889.0,64.0,badminton
1,Flipkart Customer,1.0,Don't waste your money,They didn't supplied Yonex Mavis 350. Outside ...,"Certified Buyer, Hyderabad",109.0,6.0,badminton
2,A. S. Raja Srinivasan,1.0,Did not meet expectations,Worst product. Damaged shuttlecocks packed in ...,"Certified Buyer, Dharmapuri",42.0,3.0,badminton
3,Suresh Narayanasamy,3.0,Fair,"Quite O. K. , but nowadays the quality of the...","Certified Buyer, Chennai",25.0,1.0,badminton
4,ASHIK P A,1.0,Over priced,Over pricedJust â?¹620 ..from retailer.I didn'...,unknown,147.0,24.0,badminton
...,...,...,...,...,...,...,...,...
20214,Omm Prakash,5.0,Simply awesome,Nice for red tea.Valeu for moneyREAD MORE,"Certified Buyer, Dhamanagar",26.0,5.0,tea
20215,Ritu Raj,4.0,Good choice,niceREAD MORE,"Certified Buyer, Katihar District",19.0,4.0,tea
20216,Arun Saini,1.0,Terrible product,Tata Gold Vs Tata Tea Premium👍Tata Tea Premiu...,"Certified Buyer, Haridwar",13.0,2.0,tea
20217,Amitabh Shahi,5.0,Just wow!,I believe that it's the best packaged tea in t...,"Certified Buyer, Darbhanga",32.0,10.0,tea
20218,Rohan Bhowmik,5.0,Simply awesome,Very good product.READ MORE,"Certified Buyer, Paschim Medinipur District",69.0,29.0,tea

## Step 3: Text Preprocessing

In [2]:
import re
import nltk
from nltk.corpus import stopwords

In [83]:
def get_sentiment(rating):
    if rating >= 4:
        return 'positive'
    else:
        return 'negative'

df['sentiment'] = df['reviewer_rating'].apply(get_sentiment)

In [84]:
df[['reviewer_rating', 'sentiment']].head()

   reviewer_rating sentiment
0              4.0  positive
1              1.0  negative
2              1.0  negative
3              3.0  negative
4              1.0  negative

In [85]:
def clean_text(text):
    if pd.isnull(text):   # handle NaN
        return ""
    
    text = re.sub(r'[^a-zA-Z]', ' ', str(text))
    text = text.lower()
    words = text.split()
    words = [w for w in words if w not in stopwords.words('english')]
    
    return " ".join(words)

## Step 4: Feature Engineering

In [86]:

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000)
X = vectorizer.fit_transform(df['clean_text'])

In [87]:
y = df['sentiment']

In [88]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 128917 stored elements and shape (20219, 3805)>

In [89]:
y

0        positive
1        negative
2        negative
3        negative
4        negative
           ...
20214    positive
20215    positive
20216    negative
20217    positive
20218    positive
Name: sentiment, Length: 20219, dtype: object

### Train-Test Split

In [90]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

## Model building

In [91]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [94]:
model.score(X_train, y_train)

0.9382998454404946

In [92]:
y_pred = model.predict(X_test)

## 5 Model Evaluation or test metrics

In [93]:
from sklearn.metrics import classification_report, f1_score

print(classification_report(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred, average='weighted'))

              precision    recall  f1-score   support

    negative       0.87      0.55      0.68       615
    positive       0.92      0.98      0.95      3429

    accuracy                           0.92      4044
   macro avg       0.90      0.77      0.82      4044
weighted avg       0.92      0.92      0.91      4044

F1 Score: 0.9117735428846051

## There fore test score == 93% , train accuracy == 91% so model is `Generalising `

## creating PKL file

In [96]:


import pickle

pickle.dump(model, open("model.pkl", "wb"))
pickle.dump(vectorizer, open("vectorizer.pkl", "wb"))